-- DROP TABLE
-- PROJECT DESIGNER

DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Branche;
DROP TABLE IF EXISTS Diagramme;
DROP TABLE IF EXISTS Accede;
DROP TABLE IF EXISTS Projet;
DROP TABLE IF EXISTS Utilisateur;